config/routes.rb
Rails.application.routes.draw do
  root "home#index"

  devise_for :users

  resources :photos do
    # いいねしたり、いいね解除をするurl
    resource :like
    resource :bookmark
    resources :comments
  end

  resources :users do
    resource :follow
    resources :followings
    resources :followers

    # いいね一覧を見るurl
    resources :likes

    resources :bookmarks

    resources :show
  end

  resources :talking_squids
  resources :icons


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :user
  belongs_to :photo
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :photo
end

app/models/follow.rb
class Follow < ApplicationRecord
  belongs_to :user
  belongs_to :target_user, class_name: 'User', foreign_key: 'target_user_id'
end

app/models/icon.rb
class Icon < ApplicationRecord
  has_one_attached :icon_image

  attribute :content, :string, default: 'suru-blue.png'

  before_create :default_image
  def default_image
    if !self.icon_image.attached?
      self.icon_image.attach(io: File.open(Rails.root.join('app', 'assets', 'images', 'suke_surume.png')), filename: 'suke_surume.png', content_type: 'image/png')
    end
  end
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :photo
end

app/models/photo.rb
class Photo < ApplicationRecord
  belongs_to :user

  has_many :comments
  has_many :likes
  has_many :bookmarks
  
  has_one_attached :image

  before_create :default_image

  def default_image
    if !self.image.attached?
      self.image.attach(io: File.open(Rails.root.join('app', 'assets', 'images', 'ikaline.png')), filename: 'ikaline.png', content_type: 'image/png')
    end
  end

end

app/models/talking_squid.rb
class TalkingSquid < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  has_one_attached :icon_image
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :active_relationships, class_name: 'Follow', foreign_key: 'user_id'
  has_many :passive_relationships, class_name: 'Follow', foreign_key: 'target_user_id'
  has_many :followings, through: :active_relationships, source: :target_user
  has_many :followers, through: :passive_relationships, source: :user
  
  has_many :comments
  has_many :likes
  has_many :bookmarks
  has_many :photos
  has_many :icons
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
before_action :authenticate_user!

  def index
    # current_user(ログインしているユーザー)のidと、current_userがフォローしているユーザのids(following_idsで取得できる)
    # following_idsは配列なので、*でcurrent_user.idと同じ配列に展開して渡す
    @feeds = Photo.where(user_id: [current_user.id, *current_user.following_ids]).order(created_At: :desc)

    @posts = Photo.all.order(created_at: :desc)
  end


end

app/controllers/icons_controller.rb
class IconsController < ApplicationController
  def index
    @icons = Icon.all
  end

  def show
    @icon = Icon.find(params[:id])
  end

  def new
    @icon = Icon.new()
  end

  def create
    @icon = Icon.new(icon_params)
    if @icon.save
      redirect_to edit_user_path(current_user)
    else
      render "new"
    end

  end

  def edit
    @icon = Icon.find(params[:id])
  end

  def update
    @icon = Icon.find(params[:id])
    @icon.assign_attributes(icon_params)
    if @icon.save
      redirect_to icon_path(@icon), notice: "炙り直しました"
    else
      render "edit"
    end
  end

  def destroy
    @icon = Icon.find(params[:id])
    @icon.destroy
    redirect_to icons_path, notice: "あの炙りは永久追放です" 
  end

  # ストロングパラメータ
  def icon_params
    params.require(:icon).permit(:content, :icon_image)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @icons = Icon.all
    @icon = @icons.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update 
    @user = User.find(params[:id])
    @user.assign_attributes(user_params)
    if @user.save
      redirect_to @user, notice: "更新しました"
    else
      render "edit"
    end
  end

  private
  def user_params
    params.require(:user).permit(:email, :name, :birthday, :introduction, :icon)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/followers_helper.rb
module FollowersHelper
end

app/helpers/followings_helper.rb
module FollowingsHelper
end

app/helpers/follows_helper.rb
module FollowsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/icons_helper.rb
module IconsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= render "shared/errors", obj: @user %>
<table class="lists">
  <tr>
    <th>email</th>
    <td><%= form.text_field :email %></td>
  </tr>

  <tr>
    <th><%= form.label :name, "ユーザー名" %></th>
    <td><%= form.text_field :name  %></td>
  </tr>

  <tr>
    <th><%= form.label :introduction, "自己紹介" %></th>
    <td><%= form.text_field :introduction  %></td>
  </tr>

  <tr>
    <th><%= form.label :birthday, "誕生日" %></th>
    <td>
      <%= form.date_select :birthday, start_year: 1940, end_year: Time.current.year, use_month_numbers: true %>
    </td>
  </tr>


</table>

app/views/users/edit.html.erb
<h1>user-edit</h1>
<%= link_to "するめの詳細に戻る", user_path(@user) %>
<%= form_for @user do |form| %>
  <%= render "form", form: form %>
  <div class="button"><%= form.submit %></div>
<% end %>

app/views/users/index.html.erb
<h1>ユーザー</h1>
<%= link_to "するめの入荷", new_user_path %>

<div class="icon">
  <table>
    <tr>
      <th>id</th>
      <th>email</th>
      <th>name</th>
      <th>icon</th>
      <th>操作</th>
    </tr>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.id %></td>
        <td><%= link_to user.email, user_path(user) %></td>
        <td><%= user.name %></td>
        <td><%= image_tag Icon.find(user.id).icon_image, size: "45x45" %></td>
        <td><%= link_to "編集", edit_user_path(user) %> | <%= link_to "削除", user_path(user), method: :delete, data: { confirm: "本当に削除しますか"} %></td>
      </tr>
    <% end %>
  </table>
</div>

app/views/users/show.html.erb
<div class="prof">
    <div class="prof-left">
    <% if user_signed_in? && current_user == @user %>
      <div class="icon current-user-icon">
        <%= link_to edit_icon_path(current_user) do %>
          <%= image_tag @icon.icon_image, size: "150x150", alt: "ストレージアイコン" %>
        <% end %>
      </div>
    <% else %>
      <div class="icon">
        <%= image_tag @icon.icon_image, size: "150x150", alt: "ストレージアイコン" %>
      </div>
    <% end %>

        <div class="name-box">
            <p><%= @user.name %></p>
        </div>
    </div>
    <div class="user-button">
      <% if user_signed_in? && current_user != @user %>
        <!-- followしていれば、フォロー解除ボタンを表示させる -->
        <% if current_user.active_relationships.exists?(target_user_id: @user.id) %>
          <div class="follow-button"><%= link_to 'フォロー解除', [@user, :follow], method: :delete %></div>
        <% else %>
        <!-- followしていなければ、フォローボタンを表示させる -->
          <div class="follow-button"><%= link_to 'フォロー', [@user, :follow], method: :post %></div>
        <% end %>
      <% else %>
        <div class="edit-button"><%= link_to "編集", edit_user_path %></div>
      <% end %>
    </div>
</div>
<div>
    <p class="introduction"><%= @user.introduction %></p>
</div>



  


<div class="follow">

    <div class="follow-left">
        <div class="follow-you">
            <p><%= link_to "フォロー一覧", [@user, :followings] %></p>
        </div>
        <div class="follow-me">
            <p><%= link_to "フォロワー一覧", [@user, :followers] %></p>
        </div>
    </div>
    <p class="birthday">🎈誕生日：<%= @user.birthday %></p>
</div>
<div class="user-content">
    <div class="bkm">
        <div class="bkuma-button"><%= link_to "ブックマーク一覧", [@user, :bookmarks] %></div>
    </div>
    <div class="good">
        <%= link_to "いいね", [@user, :likes] %>
    </div>
</div>

<%# user 終わり%>

<!-- 投稿画面へ -->
<%# <% if user_signed_in? && current_user == @user %> 
 <%#  <div class="post">
    <%= link_to "新しい写真を投稿する", new_photo_path %>
  <%# </div>
<% end %>

<!-- 投稿した写真を表示させる -->
 <h2>投稿一覧</h2>
  <% @user.photos.order(created_at: :desc).each do |photo| %>
  <div class="toukou">
    <div class="photo">
      <%= link_to [photo] do %>
        <%= image_tag photo.image %>
        <div class="caption"><%= photo.caption %></div>
      <% end %>
    </div>
  </div>  
  <% end %>