config/routes.rb
Rails.application.routes.draw do
  root "home#index"

  devise_for :users

  resources :photos do
    # いいねしたり、いいね解除をするurl
    resource :like
    resource :bookmark
    resources :comments
  end

  resources :users do
    resource :follow
    resources :followings
    resources :followers

    # いいね一覧を見るurl
    resources :likes

    resources :bookmarks

    resources :show
  end

  resources :talking_squids
  resources :icons


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :user
  belongs_to :photo
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :photo
end

app/models/follow.rb
class Follow < ApplicationRecord
  belongs_to :user
  belongs_to :target_user, class_name: 'User', foreign_key: 'target_user_id'
end

app/models/icon.rb
class Icon < ApplicationRecord
  has_one_attached :icon_image

  attribute :content, :string, default: 'suru-blue.png'

  before_create :default_image
  def default_image
    if !self.icon_image.attached?
      self.icon_image.attach(io: File.open(Rails.root.join('app', 'assets', 'images', 'suke_surume.png')), filename: 'suke_surume.png', content_type: 'image/png')
    end
  end
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :photo
end

app/models/photo.rb
class Photo < ApplicationRecord
  belongs_to :user

  has_many :comments
  has_many :likes
  has_many :bookmarks
  
  has_one_attached :image

  before_create :default_image

  def default_image
    if !self.image.attached?
      self.image.attach(io: File.open(Rails.root.join('app', 'assets', 'images', 'ikaline.png')), filename: 'ikaline.png', content_type: 'image/png')
    end
  end

end

app/models/talking_squid.rb
class TalkingSquid < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  has_one_attached :icon_image
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :active_relationships, class_name: 'Follow', foreign_key: 'user_id'
  has_many :passive_relationships, class_name: 'Follow', foreign_key: 'target_user_id'
  has_many :followings, through: :active_relationships, source: :target_user
  has_many :followers, through: :passive_relationships, source: :user
  
  has_many :comments
  has_many :likes
  has_many :bookmarks
  has_many :photos
  has_many :icons
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/followers_helper.rb
module FollowersHelper
end

app/helpers/followings_helper.rb
module FollowingsHelper
end

app/helpers/follows_helper.rb
module FollowsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/icons_helper.rb
module IconsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>abutter</title>
    <%= favicon_link_tag('favicon.ico') %>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header class="header">
      <%= render "shared/header" %>
    </header>

    <div class="flex-box">
      <main class="main">
      <%= yield %>
      </main>
      
      <aside class="sidebar-l">
      <%= render "shared/sidebar-l" %>
      </aside>
      
      <aside class="sidebar-r">
      <%= render "shared/sidebar-r" %>
      </aside>
      
      <footer class="footer">
      
      </footer>
    </div>

    
  </body>
</html>

app/views/layouts/devise.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>abutter</title>
    <%= favicon_link_tag('favicon.ico') %>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= favicon_link_tag '/favicon.ico' %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header class="header">
      <%= render "shared/header" %>
    </header>

    <div class="devise-form">
      <main class="devise-field">
        <%= yield %>
      </main>

      <div class="devise-image">
        <%= image_tag("surumekun.png", size:"180x180") %>
      </div>
      
      <footer class="footer">
      
      </footer>
    </div>

    
  </body>
</html>

app/views/shared/_errors.html.erb
<% if obj.errors.present? %>
  <div id="errors">
    <h3>エラーがあります</h3>
    <ul>
      <% obj.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %> 

app/views/shared/_footer.html.erb
Copyright(c) 

app/views/shared/_header.html.erb
<div class="header-logo">
  <%= link_to root_path do %>
    <%= image_tag "abutter.png" %>
  <% end %>
</div>

app/views/shared/_login_form.html.erb
<h2>log in</h2>

<% if flash.alert %>
  <p class="alert"><%= flash.alert %></p>
<% end %>

<%= form_tag :session, id:"login_form" do %>
  <div>
    <label>user: </label>
    <input type="text" name="name">
  </div>
  <div>
    <label>password: </label>
    <input type="password" name="password">
  </div>
  <div>
    <input type="submit" name="ログイン">
  </div>
  
<% end %>

app/views/shared/_sidebar-l.html.erb
<nav>
    <div class="hello">
      <% if Icon.exists?(id: current_user.id) %>
        <p>こんにちは、<%= current_user.name %> さん</p>
      <% end %>
    </div>
  <ul>
    
    <li><%= link_to "ホーム", root_path %></li>
    <li><%= link_to "ブックマーク一覧", user_bookmarks_path(current_user) %></li>
    <% if Icon.exists?(id: current_user.id) %>
      <li><%= link_to "マイページ", user_path(current_user) %></li>
    <% end %>
    <li><%= link_to "投稿", new_photo_path %></li>
    <li><%= link_to "みんなの投稿一覧", photos_path %></li>
    
  </ul>

  <div class="config">
    <%= link_to "ログアウト", destroy_user_session_path, method: :delete %>
  </div>

  <div class="user-information">ユーザー一覧</div>
  <div class="usernum">
    <p>
      現在<%= User.count %>人
    </p>
  </div>
  <div class="user_index">
    <div class="user-listbox">
      <% User.all.each do |user| %>
        <div class="user-list">
          <%= link_to user.name, user_path(user) %>
        </div>
      <% end %>
    </div>
  </div>

  <!-- id==1のユーザー（管理者）オンリー -->
  <% if (current_user.id == 1) %>
  <div class="admin">
    <h3>
      <p>
        管理ページ
      </p>
      <!--
      <p>
        現在<%= User.count %>人
      </p>-->
    </h3>
    <ul>
      <%= link_to "ユーザ一覧", users_path %>
    
      <%= link_to "アイコン一覧", icons_path %>
     
      <%= link_to "あぶり一覧", talking_squids_path %>
    </ul>
  </div>
<% end %>


</nav>

app/views/shared/_sidebar-r.html.erb
<% num = TalkingSquid.all.size %>
<div class="surucom">
  <div class="tweet">
    <p>
      <%= TalkingSquid.all.find(rand(1..num)).comment %>
    </p>
  </div>
  <div class="ika-sugata">
    <%= image_tag("surumekun.png", size:"180x180") %>
  </div>
</div>

<hr>