config/routes.rb
Rails.application.routes.draw do
  root "home#index"

  devise_for :users

  resources :photos do
    # いいねしたり、いいね解除をするurl
    resource :like
    resource :bookmark
    resources :comments
  end

  resources :users do
    resource :follow
    resources :followings
    resources :followers

    # いいね一覧を見るurl
    resources :likes

    resources :bookmarks

    resources :show
  end

  resources :talking_squids
  resources :icons


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :user
  belongs_to :photo
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :photo
end

app/models/follow.rb
class Follow < ApplicationRecord
  belongs_to :user
  belongs_to :target_user, class_name: 'User', foreign_key: 'target_user_id'
end

app/models/icon.rb
class Icon < ApplicationRecord
  has_one_attached :icon_image

  attribute :content, :string, default: 'suru-blue.png'

  before_create :default_image
  def default_image
    if !self.icon_image.attached?
      self.icon_image.attach(io: File.open(Rails.root.join('app', 'assets', 'images', 'suke_surume.png')), filename: 'suke_surume.png', content_type: 'image/png')
    end
  end
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :photo
end

app/models/photo.rb
class Photo < ApplicationRecord
  belongs_to :user

  has_many :comments
  has_many :likes
  has_many :bookmarks
  
  has_one_attached :image

  before_create :default_image

  def default_image
    if !self.image.attached?
      self.image.attach(io: File.open(Rails.root.join('app', 'assets', 'images', 'ikaline.png')), filename: 'ikaline.png', content_type: 'image/png')
    end
  end

end

app/models/talking_squid.rb
class TalkingSquid < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  has_one_attached :icon_image
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :active_relationships, class_name: 'Follow', foreign_key: 'user_id'
  has_many :passive_relationships, class_name: 'Follow', foreign_key: 'target_user_id'
  has_many :followings, through: :active_relationships, source: :target_user
  has_many :followers, through: :passive_relationships, source: :user
  
  has_many :comments
  has_many :likes
  has_many :bookmarks
  has_many :photos
  has_many :icons
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
before_action :authenticate_user!

  def index
    # current_user(ログインしているユーザー)のidと、current_userがフォローしているユーザのids(following_idsで取得できる)
    # following_idsは配列なので、*でcurrent_user.idと同じ配列に展開して渡す
    @feeds = Photo.where(user_id: [current_user.id, *current_user.following_ids]).order(created_At: :desc)

    @posts = Photo.all.order(created_at: :desc)
  end


end

app/controllers/icons_controller.rb
class IconsController < ApplicationController
  def index
    @icons = Icon.all
  end

  def show
    @icon = Icon.find(params[:id])
  end

  def new
    @icon = Icon.new()
  end

  def create
    @icon = Icon.new(icon_params)
    if @icon.save
      redirect_to edit_user_path(current_user)
    else
      render "new"
    end

  end

  def edit
    @icon = Icon.find(params[:id])
  end

  def update
    @icon = Icon.find(params[:id])
    @icon.assign_attributes(icon_params)
    if @icon.save
      redirect_to icon_path(@icon), notice: "炙り直しました"
    else
      render "edit"
    end
  end

  def destroy
    @icon = Icon.find(params[:id])
    @icon.destroy
    redirect_to icons_path, notice: "あの炙りは永久追放です" 
  end

  # ストロングパラメータ
  def icon_params
    params.require(:icon).permit(:content, :icon_image)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/followers_helper.rb
module FollowersHelper
end

app/helpers/followings_helper.rb
module FollowingsHelper
end

app/helpers/follows_helper.rb
module FollowsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/icons_helper.rb
module IconsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.erb
<%# 新規登録時にアイコンが設定されていないとエラーになるのでここでアイコン登録を促すためにリンクの表示を切り替える %>
<% if Icon.exists?(id: current_user.id) %>
  <div class="mypage-icon">
    <%= link_to user_path(current_user) do %>
      <%= image_tag Icon.find(current_user.id).icon_image, size: "80", class: "name-icon" %>
    <% end %>
    <%= link_to current_user.name, user_path(current_user), class: "name-tag" %>
  </div>
<% else %>
  <div class="アイコン">
    <%=  link_to "iconを登録してね", new_icon_path %>
  </div>
<% end %>

<hr>

<!-- サインアウト用のリンク クリックするとhome(ログインしていないのでlog inに飛ぶ) -->


<!-- 写真投稿用のページへ -->
<div class="home-posts">
  <%=  link_to "投稿する", new_photo_path %>
</div>

<!-- icon設定のページへ -->
<%# <div class="アイコン"> %>
  <%# <%=  link_to "icon登録", new_user_icon_path %> 
<%# </div> %>

<!-- timeline -->
<!-- （ここに自分とフォローしているユーザの投稿一覧を表示させる） -->
<!-- （写真をクリックすると投稿写真の詳細ページへ飛んで、コメントを送信したりいいねをしたりできる） -->

<!-- 投稿一覧を表示させる -->
<% @feeds.each do |photo| %>

  <div class="toukou">
    <hr>
    <!-- 投稿者のメールアドレス表示させる(link先は投稿者のユーザーページ) -->
    <div class="home-user-information">
      <div class = "home-user-name">
        <%= link_to photo.user.name, [photo.user] %>
      </div>
    </div>
    <!-- photo -->
    <div class="home-photo">
      <%= link_to [photo] do %>
        <%= image_tag photo.image%>
      <% end %>
    </div>
    <!-- caption -->
    <div class="home-caption"><%= photo.caption %></div>
    <hr>
  </div>
<% end %>