config/routes.rb
Rails.application.routes.draw do
  root "home#index"

  devise_for :users

  resources :photos do
    # いいねしたり、いいね解除をするurl
    resource :like
    resource :bookmark
    resources :comments
  end

  resources :users do
    resource :follow
    resources :followings
    resources :followers

    # いいね一覧を見るurl
    resources :likes

    resources :bookmarks

    resources :show
  end

  resources :talking_squids
  resources :icons


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :user
  belongs_to :photo
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :photo
end

app/models/follow.rb
class Follow < ApplicationRecord
  belongs_to :user
  belongs_to :target_user, class_name: 'User', foreign_key: 'target_user_id'
end

app/models/icon.rb
class Icon < ApplicationRecord
  has_one_attached :icon_image

  attribute :content, :string, default: 'suru-blue.png'

  before_create :default_image
  def default_image
    if !self.icon_image.attached?
      self.icon_image.attach(io: File.open(Rails.root.join('app', 'assets', 'images', 'suke_surume.png')), filename: 'suke_surume.png', content_type: 'image/png')
    end
  end
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :photo
end

app/models/photo.rb
class Photo < ApplicationRecord
  belongs_to :user

  has_many :comments
  has_many :likes
  has_many :bookmarks
  
  has_one_attached :image

  before_create :default_image

  def default_image
    if !self.image.attached?
      self.image.attach(io: File.open(Rails.root.join('app', 'assets', 'images', 'ikaline.png')), filename: 'ikaline.png', content_type: 'image/png')
    end
  end

end

app/models/talking_squid.rb
class TalkingSquid < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  has_one_attached :icon_image
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :active_relationships, class_name: 'Follow', foreign_key: 'user_id'
  has_many :passive_relationships, class_name: 'Follow', foreign_key: 'target_user_id'
  has_many :followings, through: :active_relationships, source: :target_user
  has_many :followers, through: :passive_relationships, source: :user
  
  has_many :comments
  has_many :likes
  has_many :bookmarks
  has_many :photos
  has_many :icons
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
before_action :authenticate_user!

  def index
    # current_user(ログインしているユーザー)のidと、current_userがフォローしているユーザのids(following_idsで取得できる)
    # following_idsは配列なので、*でcurrent_user.idと同じ配列に展開して渡す
    @feeds = Photo.where(user_id: [current_user.id, *current_user.following_ids]).order(created_At: :desc)

    @posts = Photo.all.order(created_at: :desc)
  end


end

app/controllers/talking_squids_controller.rb
class TalkingSquidsController < ApplicationController
  def index
    @surumes = TalkingSquid.all
  end

  def show
    @surume = TalkingSquid.find(params[:id])
  end

  def new
    @surume = TalkingSquid.new()
  end

  def create
    @surume = TalkingSquid.new(ika_params)
    if @surume.save
      redirect_to talking_squids_path, notice: "また炙ってしまった..."
    else
      render "new"
    end

  end

  def edit
    @surume = TalkingSquid.find(params[:id])
  end

  def update
    @surume = TalkingSquid.find(params[:id])
    @surume.assign_attributes(ika_params)
    if @surume.save
      redirect_to talking_squids_path, notice: "炙りなおしました"
    else
      render "edit"
    end
  end

  def destroy
    @surume = TalkingSquid.find(params[:id])
    @surume.destroy
    redirect_to talking_squids_path, notice: "炙りが過ぎたので消し炭にしました"

  end

  private
  def ika_params
    params.require(:talking_squid).permit(:comment)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/followers_helper.rb
module FollowersHelper
end

app/helpers/followings_helper.rb
module FollowingsHelper
end

app/helpers/follows_helper.rb
module FollowsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/icons_helper.rb
module IconsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/talking_squids_helper.rb
module TalkingSquidsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/talking_squids/_form.html.erb
<%= render "shared/errors", obj: @surume %>
<table class="lists">
  <tr>
    <th><%= form.label :comment, "炙り" %></th>
    <td><%= form.text_field :comment %></td>
  </tr>
  


</table>

app/views/talking_squids/edit.html.erb
<h1>炙りなおす</h1>
<%= link_to "炙り詳細に戻る", talking_squid_path(@surume) %>
<%= form_for @surume do |form| %>
  <%= render "form", form: form %>
  <div class="button"><%= form.submit %></div>
<% end %>

app/views/talking_squids/index.html.erb
<h1>するめのindex</h1>

<%= link_to "するめのindex", talking_squids_path %>
<%= link_to "するめのnew", new_talking_squid_path %>


<h2>あぶ履歴一覧</h2>

<div class="toolbar"><%= link_to "新規登録", new_talking_squid_path %></div>

<% if @surumes.present? %>
  <table class="lists">
    <thead>
      <tr>
        <th>炙りメニュー</th>
        <th>操作</th>

      </tr>
    </thead>

    <tbody>
      <% @surumes.each do |surume| %>
        <tr>
          <td><%= link_to surume.comment, talking_squid_path(surume) %></td>
          <td><%= link_to "編集", edit_talking_squid_path(surume) %> <%#= link_to "削除", talking_squid_path(surume), method: :delete, data: { confirm: "本当に削除しますか"} %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <p>炙っていないようです。</p>
<% end %>

<%= link_to "TOPへ", root_path %>

app/views/talking_squids/new.html.erb
<h1>新規炙り</h1>
<div class="toolbar"><%= link_to "炙り履歴一覧に戻る", talking_squids_path %></div>


<%= form_for @surume do |form| %>
  <%= render "form", form: form %>
  <div class="button"><%= form.submit %></div>
<% end %>

app/views/talking_squids/show.html.erb
するめのshow
<div><%= link_to "編集", edit_talking_squid_path(@surume) %></div>

<table class="lists">
  <tr>
    <th>炙りメニュー</th>
    <td><%= @surume.comment %></td>
  </tr>


</table>